serenity.project.name = Taller Semana 4 E2E Tests
webdriver.driver = chrome
# headless.mode = false
serenity.console.colors = true
webdriver.base.url = http://localhost:5173
chrome.switches = --remote-allow-origins=*
webdriver.timeouts.implicitlywait = 10000
serenity.timeout = 10000
